### ISSUE TITLE
Can not select the desired gamma when it's the same level as the menu bar

### ISSUE THREAD

**Issue by furutaka** [sandialabs/InterSpec#12] opened 2022-03-18 06:08 UTC
Now I'm using v.1.0.9 of the software.

When doing "Change Nuclide", often the desired gamma is at the top level of the choices and on the same level as the menu bar; in that case, it can not be selected... (In the case of the attached figures, I wanted to assign the peak to Sb124(602.73keV))
It's only a minor issue, as the choice can be selected and set through the "Peak Editor".  But it is more easy if I can do so by "Change Nuclide".
I'm afraid this may be due to the toolkit used (Qt?), but anyway I'll report this.

By the way, I have a few questions and feature requests; can I post them here? or is it better to send an e-mail to the address in "Disclaimers, Licenses, Credit, and Contact"?

Thanks in advance,
Kazuyosh
![WS000194](https://user-images.githubusercontent.com/1713040/158946765-1030f0b5-07bc-4b0b-9b6e-fbc2bbc251da.JPG)
![WS000195](https://user-images.githubusercontent.com/1713040/158946767-4b88e7e6-272f-41d9-8591-852a6b73cb46.JPG)
i

**Comment by wcjohns** [comment] 2022-03-18 16:40
Once again, thank you very much for this bug report!

I was able to finally reproduce.

Looks like it was an interference between the [Electron](https://www.electronjs.org) specific CSS that allows dragging the whole window around by the titlebar (i.e. `-webkit-app-region: drag;`) and the context menu.  

I've found a likely fix (add a 25px margin to the top of sub-context menus), but want to test more before closing the issue.

This issue seems to effect the Electron builds of InterSpec (i.e., Windows and Linux), and only when the list of suggested nuclides is very long.  Which I guess is why I hadn't noticed it before since I mostly use the web-based or macOS versions of InterSpec.

For questions or feature requests, yes, please email InterSpec@sandia.gov and I'll be very happy to answer.

thank you again,
  -will

**Closed** 2022-03-19 15:52 UTC
